FROM itamtao/tensorflow-basis
MAINTAINER Tao Lin <itamtao@gmail.com>


# install Tensorflow GPU Version
ENV TENSORFLOW_VERSION 1.2.1
RUN pip --no-cache-dir install \
    http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-${TENSORFLOW_VERSION}-cp27-none-linux_x86_64.whl


# install other python packages related to tensorflow
RUN pip --no-cache-dir install tflearn tensorlayer
