version: '3.9'
services:
    base:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: base/Dockerfile
        image:  itamtao/base
    pytorch-mpi:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: pytorch-mpi/Dockerfile
        image:  itamtao/pytorch-mpi
        depends_on:
            - base

