version: '3.9'
services:
    base:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: base/Dockerfile
        image:  itamtao/base
    pytorch-mpi:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: pytorch-mpi/Dockerfile
            args:
                http_proxy: http://192.168.123.169:18889
                https_proxy: http://192.168.123.169:18889
        image: itamtao/pytorch-mpi
        depends_on:
            - base
