FROM itamtao/jupyter-base-notebook:latest
MAINTAINER Tao Lin <itamtao@gmail.com>

RUN pip2 install --no-cache-dir numpy
RUN pip3 install --no-cache-dir matplotlib


RUN pip2 install --no-cache-dir scipy


# install matplotlib
RUN pip2 install --no-cache-dir matplotlib
RUN pip3 install --no-cache-dir matplotlib


# install scikit-learn
RUN pip2 install --no-cache-dir scikit-learn

# install ipython
RUN pip2 install --no-cache-dir ipython
RUN pip3 install --no-cache-dir ipython


# install joblib
RUN pip2 install --no-cache-dir joblib

# install pandas
RUN pip2 install --no-cache-dir pandas

# install cython
RUN pip2 install --no-cache-dir cython

# Install python package
RUN pip2 install --no-cache-dir xlrd pyquery beautifulsoup4

RUN pip2 install --no-cache-dir nltk

RUN pip3 install --no-cache-dir ipywidgets
